#!/usr/bin/env bash
# =============================================================================
#  sysinfo.sh — System Information Script
#  Saswata Das (24BCS10248) — Shell Scripting homework
#
#  Requirement checklist (all implemented below):
#    [x] prints the current date              -> date
#    [x] prints the hostname                  -> hostname
#    [x] prints the username                  -> whoami
#    [x] prints the disk usage                -> df -h
#    [x] prints the running processes         -> ps -ef / ps aux
#    [x] uses variables to store and use data
#    [x] takes user input using read -p
#    [x] creates a directory using mkdir
#    [x] creates a file using touch
#    [x] stores running processes in the file using > output redirection
# =============================================================================

# ---------------------------------------------------------------------------
# 1. VARIABLES — collect the data once, reuse it everywhere
# ---------------------------------------------------------------------------
CURRENT_DATE=$(date)                       # command substitution into a variable
DATE_STAMP=$(date +%Y-%m-%d_%H-%M-%S)      # filesystem-safe timestamp
HOST_NAME=$(hostname)
USER_NAME=$(whoami)
KERNEL=$(uname -sr)
UPTIME_INFO=$(uptime)
SCRIPT_NAME=$(basename "$0")

echo "==========================================================="
echo "            SYSTEM INFORMATION REPORT"
echo "            generated by $SCRIPT_NAME"
echo "==========================================================="
echo

# ---------------------------------------------------------------------------
# 2. PRINT THE BASIC SYSTEM INFO (using the variables set above)
# ---------------------------------------------------------------------------
echo "--- 1. Current Date ---"
echo "Current date and time : $CURRENT_DATE"
echo

echo "--- 2. Hostname ---"
echo "Hostname              : $HOST_NAME"
echo

echo "--- 3. Username ---"
echo "Logged in as          : $USER_NAME"
echo "User ID details       : $(id)"
echo

echo "--- Extra context ---"
echo "Kernel                : $KERNEL"
echo "Uptime                : $UPTIME_INFO"
echo

# ---------------------------------------------------------------------------
# 3. DISK USAGE  (df)
# ---------------------------------------------------------------------------
echo "--- 4. Disk Usage (df -h) ---"
df -h
echo
echo "Disk usage of the root filesystem only:"
ROOT_USAGE=$(df -h / 2>/dev/null | awk 'NR==2 {print $5 " used of " $2}')   # store into a variable
echo "Root filesystem       : $ROOT_USAGE"
echo

# ---------------------------------------------------------------------------
# 4. RUNNING PROCESSES  (ps)
# ---------------------------------------------------------------------------
echo "--- 5. Running Processes (ps -ef | head -10) ---"
# stderr is silenced because `head` closes the pipe early, which makes ps
# print a harmless "Broken pipe" warning on BSD/macOS.
ps -ef 2>/dev/null | head -10
echo

# `ps -e --no-headers` is GNU/procps-only, so fall back to trimming the header
# manually on BSD/macOS. Note the fallback must be chosen by testing ps itself:
# putting `||` after a pipeline would test `wc -l`, which always succeeds.
if ps -e --no-headers >/dev/null 2>&1; then
    PROCESS_COUNT=$(ps -e --no-headers 2>/dev/null | wc -l | tr -d ' ')
else
    PROCESS_COUNT=$(ps -e 2>/dev/null | tail -n +2 | wc -l | tr -d ' ')
fi
echo "Total running processes: $PROCESS_COUNT"
echo

# ---------------------------------------------------------------------------
# 5. USER INPUT with read -p
# ---------------------------------------------------------------------------
echo "==========================================================="
echo "  Now we will save this report to a file you name."
echo "==========================================================="
echo

read -p "Enter a name for the report directory : " DIR_NAME
read -p "Enter a name for the report file      : " FILE_NAME
read -p "Enter your name (report author)       : " AUTHOR

# Fall back to sensible defaults if the user just pressed Enter
DIR_NAME=${DIR_NAME:-sysinfo_reports}
FILE_NAME=${FILE_NAME:-processes}
AUTHOR=${AUTHOR:-$USER_NAME}

echo
echo "You entered:"
echo "  directory : $DIR_NAME"
echo "  file      : $FILE_NAME"
echo "  author    : $AUTHOR"
echo

# ---------------------------------------------------------------------------
# 6. CREATE THE DIRECTORY with mkdir
# ---------------------------------------------------------------------------
echo "--- 6. Creating directory with mkdir ---"
mkdir -p "$DIR_NAME"
echo "\$ mkdir -p $DIR_NAME"
ls -ld "$DIR_NAME"
echo

# ---------------------------------------------------------------------------
# 7. CREATE THE FILE with touch
# ---------------------------------------------------------------------------
# Build the full path in a variable, then create the empty file with touch
REPORT_FILE="$DIR_NAME/${FILE_NAME}_${DATE_STAMP}.txt"

echo "--- 7. Creating file with touch ---"
touch "$REPORT_FILE"
echo "\$ touch $REPORT_FILE"
ls -l "$REPORT_FILE"
echo "(size is 0 — the file exists but is empty)"
echo

# ---------------------------------------------------------------------------
# 8. STORE THE RUNNING PROCESSES IN THE FILE using > OUTPUT REDIRECTION
# ---------------------------------------------------------------------------
echo "--- 8. Writing running processes into the file with > redirection ---"

# ">" creates/overwrites the file
echo "System Information Report" > "$REPORT_FILE"

# ">>" appends to it
echo "Author        : $AUTHOR"        >> "$REPORT_FILE"
echo "Generated on  : $CURRENT_DATE"  >> "$REPORT_FILE"
echo "Hostname      : $HOST_NAME"     >> "$REPORT_FILE"
echo "Username      : $USER_NAME"     >> "$REPORT_FILE"
echo "Kernel        : $KERNEL"        >> "$REPORT_FILE"
echo ""                               >> "$REPORT_FILE"
echo "=== DISK USAGE (df -h) ==="     >> "$REPORT_FILE"
df -h                                 >> "$REPORT_FILE"
echo ""                               >> "$REPORT_FILE"
echo "=== RUNNING PROCESSES (ps -ef) ===" >> "$REPORT_FILE"

# The required step: running processes stored in the file via > redirection.
# (Using >> here because we are appending to the header we just built; the
#  pure ">" form is demonstrated on the dedicated file below.)
ps -ef >> "$REPORT_FILE"

# A second file written with a PURE ">" redirect, exactly as the task words it:
PROC_ONLY_FILE="$DIR_NAME/${FILE_NAME}_processes_only.txt"
touch "$PROC_ONLY_FILE"
ps -ef > "$PROC_ONLY_FILE"          # <-- running processes stored using >

echo "\$ ps -ef > $PROC_ONLY_FILE"
echo

# ---------------------------------------------------------------------------
# 9. VERIFY
# ---------------------------------------------------------------------------
echo "--- 9. Verification ---"
echo "\$ ls -l $DIR_NAME"
ls -l "$DIR_NAME"
echo
echo "\$ wc -l $REPORT_FILE"
wc -l "$REPORT_FILE"
echo
echo "--- First 25 lines of the generated report ---"
head -25 "$REPORT_FILE"
echo
echo "--- Proof the > redirect wrote the process list ---"
echo "\$ head -5 $PROC_ONLY_FILE"
head -5 "$PROC_ONLY_FILE"
echo "\$ wc -l $PROC_ONLY_FILE"
wc -l "$PROC_ONLY_FILE"
echo
echo "==========================================================="
echo " Report saved to: $REPORT_FILE"
echo " Done."
echo "==========================================================="
