apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskapi.fullname" . }}
  labels: {{- include "taskapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: [{ port: {{ .Values.service.port }}, targetPort: http, name: http }]
  selector: {{- include "taskapi.selectorLabels" . | nindent 4 }}
