apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-api-data
  namespace: finalproject
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: standard     # dynamic provisioning
  resources:
    requests: { storage: 128Mi }
