#!/usr/bin/env bash
# Networking command practice — every command actually executed.
set -u
hr(){ echo; echo "==================== $* ===================="; }
run(){ echo; echo "\$ $*"; eval "$@" 2>&1 | head -${N:-20}; }

hr "1. INTERFACES — ip addr / ifconfig"
run "ip addr show"
run "ip -brief addr show"
run "ifconfig"
run "ip link show"
run "hostname"
run "hostname -I"
run "cat /sys/class/net/eth0/address"

hr "2. ROUTING TABLE — ip route / route"
run "ip route show"
run "ip route get 8.8.8.8"
run "route -n"
echo
echo ">> 'default via <gw> dev eth0' is the DEFAULT GATEWAY: where packets go"
echo ">> when no more specific route matches."

hr "3. ARP / NEIGHBOUR TABLE"
run "ip neigh show"
run "arp -a"

hr "4. DNS RESOLUTION — dig / nslookup / host"
run "cat /etc/resolv.conf"
run "cat /etc/hosts"
N=25 run "dig github.com"
run "dig +short github.com"
run "dig +short google.com A"
run "dig +short google.com AAAA"
run "dig +short google.com MX"
run "dig +short -x 8.8.8.8"
run "nslookup github.com"
run "host github.com"
run "getent hosts github.com"

hr "5. CONNECTIVITY — ping"
run "ping -c 4 8.8.8.8"
run "ping -c 4 google.com"
echo
echo ">> ping sends ICMP Echo Request and waits for Echo Reply."
echo ">> 'time=' is round-trip latency; '0% packet loss' means the path is clean."

hr "6. PATH TO A HOST — traceroute"
N=25 run "traceroute -m 12 -w 1 google.com"
echo
echo ">> Each hop is a router. traceroute increments the TTL so each router in turn"
echo ">> replies with 'time exceeded', revealing the path. '*' = no reply (filtered)."

hr "7. SOCKETS & LISTENING PORTS — ss / netstat"
# start a listener so there is something real to see
nc -l -p 9000 >/dev/null 2>&1 &
NCPID=$!
sleep 1
run "ss -tuln"
run "ss -tulnp"
run "netstat -tuln"
run "netstat -tulnp"
run "ss -s"
echo
echo ">> -t TCP  -u UDP  -l listening  -n numeric (no DNS lookups)  -p owning process"
kill $NCPID 2>/dev/null || true

hr "8. TESTING A PORT — nc / telnet"
run "nc -zv -w 3 google.com 443"
run "nc -zv -w 3 google.com 80"
run "nc -zv -w 2 google.com 12345"
echo
echo ">> nc -z = scan only (send nothing), -v = verbose, -w = timeout."
echo ">> This is how you prove 'is the port actually open?' without a client."

hr "9. HTTP — curl / wget"
run "curl -I https://github.com"
run "curl -s -o /dev/null -w 'http_code=%{http_code}\\ndns=%{time_namelookup}s\\nconnect=%{time_connect}s\\ntls=%{time_appconnect}s\\ntotal=%{time_total}s\\n' https://github.com"
run "curl -s https://api.github.com/zen"
run "curl -s ifconfig.me"
echo
run "wget -qO- https://api.github.com/zen"
run "wget --spider -S https://github.com 2>&1 | head -12"

hr "10. PACKET CAPTURE — tcpdump"
echo
echo "\$ tcpdump -i any -c 5 -n icmp   (capture 5 ICMP packets while pinging)"
timeout 15 tcpdump -i any -c 5 -n icmp 2>/dev/null &
TDPID=$!
sleep 2
ping -c 3 8.8.8.8 >/dev/null 2>&1
wait $TDPID 2>/dev/null || true
echo
echo ">> tcpdump reads packets straight off the wire. This capture shows the ICMP"
echo ">> echo request/reply pairs generated by the ping above."

hr "11. PORT SCAN — nmap (localhost only)"
nc -l -p 9001 >/dev/null 2>&1 &
NC2=$!
sleep 1
N=25 run "nmap -sT -p 1-1024,9001 127.0.0.1"
kill $NC2 2>/dev/null || true
echo
echo ">> Only 127.0.0.1 (this container itself) is scanned. Scanning hosts you do"
echo ">> not own is unauthorised and in many places illegal."

hr "12. NETWORK STATS & MTU"
run "ip -s link show eth0"
run "cat /proc/net/dev"
run "ip link show eth0 | grep -o 'mtu [0-9]*'"

hr "13. WHOIS"
N=20 run "whois github.com"

hr "14. COMMANDS EXPLAINED BUT NOT RUN HERE"
cat <<'NOTE'

  ssh user@host            - encrypted remote shell (port 22). Needs a remote host.
  scp file user@host:/path - copy files over SSH.
  rsync -avz src host:dst  - efficient delta-based sync over SSH.
  iptables -L -n -v        - list firewall rules (needs NET_ADMIN; superseded by nftables).
  ufw status               - Ubuntu's friendly firewall front-end.
  mtr google.com           - traceroute + ping combined, continuously updating (interactive).
  tcpdump -w cap.pcap      - write a capture to disk for Wireshark.
  ip addr add 10.0.0.5/24 dev eth0   - assign an IP manually.
  ip route add 10.0.0.0/24 via 192.168.1.1  - add a static route.

NOTE

echo
echo "==================== NETWORKING PRACTICE COMPLETE ===================="
